### ISSUE TITLE
FYI: ansible galaxy fork

### ISSUE THREAD

**Issue by zyphlar** [fukawi2/unifi-controller-rhel#1]
Hi there, I needed to use this as a role instead of a playbook, so I rewrote it into that format and put it on Ansible Galaxy:

- https://github.com/zyphlar/unifi_controller_rhel
- https://galaxy.ansible.com/zyphlar/unifi_controller_rhel/

If you'd like to work together to backport or improve the code, or publish on Galaxy under your name, I am more than happy to do so... otherwise, happy coding and hopefully everything is alright. Thanks for publishing this, it saved me many hours!

**Comment by fukawi2** [comment]
Thanks for letting me know -- I'm not sure I ever actually even got this working (I gave up and used the official Debian repos from ubnt) so I'm glad it was helpful :)

**Comment by zyphlar** [comment]
There were a few typos but it worked for me!
